### ISSUE TITLE
Not storing empty MVT tiles

### ISSUE THREAD

**Issue by rwrx** [tilezen/tilepacks#9]
Is it somehow possible to check MVT (I am aware that geojson can be easily checked) tile after it is fetched from tile server that it does not contain any data and not store it into MBTiles or zip file? Because in some areas there are plenty of empty tiles in higher zoom levels and I think that it is not necessary to store them. By empty tiles I mean that they does not contain any features.

**Comment by nvkelso** [comment]
MBTiles has a feature that may take care of this for you automatically
(it’s useful for “empty” “water" tiles), we’d would need to confirm that’s
working for this config – you could verify that with existing setup. For
ZIP that’d be a new feature, we’re happy to take pull requests here.

Caution that your technique must be paired with a map style that default
“no tile data” to either a “land" color or a “water” color else the map
will look like it has holes in it. For most (all?) Mapzen basemap styles
that’s specified for the land (e.g.: scene: { background: { color:
global.earth1 }). You could swap that for water easily enough with a scene
file YAML import or JS mix-in (only the scene file YAML import is supported
at this time on ES).

**Comment by rwrx** [comment]
I am not sure how to verify it, but to me it seems that it is not taking care of this automatically when I look at generated MBTiles files. They have all the tiles.

**Comment by nvkelso** [comment]
This thread has good background reading for you:
https://github.com/osm2vectortiles/osm2vectortiles/issues/42

**Comment by rwrx** [comment]
Thank you a lot for this link. I have added into tilepack code to not store tiles which contains only one earth feature and zero other features. This will basically omit all tiles which are empty "earth" tiles. Thank you. I will close this issue.
